### ISSUE TITLE
support Windows Phone

### ISSUE THREAD

**Issue by Susinmn** [teamstudio/xcontrols-domino#256]
Do you plan to support Windows Phone?
I use Android css for Windows Phone.

**Comment by whitemx** [comment]
Hi,

While we have not done any specific testing on Windows Phone, we do test on IE on the desktop so, if you are happy to use the Android CSS then yes there is no reason you can't use IE on Windows Phone. 

We have heard from someone who has done this with a Nokia 521 and it works OK.

Matt

**Comment by Susinmn** [comment]
Matt, application also looks great on BB10. Maybe add in controls?

In unp/unplugged.js:

unp.isWindowsPhone = function() {
	return /windows phone/i.test(navigator.userAgent.toLowerCase());
}

unp.isBB = function() {
	return /bb10/i.test(navigator.userAgent.toLowerCase());
}

if (unp.isIOS() || unp.isAndroid() || unp.isWindowsPhone() || unp.isBB()) {
		var navbarheight = 0;
		$('.navbar').each( function() {
			navbarheight += $(this).height();
		})
		$(".fullheightrow").height(($(window).height() - 44));
	}

if (unp.isIOS() || unp.isAndroid() || unp.isWindowsPhone() || unp.isBB()) {
		$('#list')
				.scroll(
						function() {
							if ($(this)[0].scrollHeight - $(this).scrollTop() == $(
									this).outerHeight()) {
								unp.doflatviewscroll();
							}
							
						});
	} else {

In unpCommon ssjs:

function isWindowsPhone(){
	if (context.getUserAgent().getUserAgent().indexOf("Windows Phone") > -1){
		return true;
	}else{
		return false;
	}
}

function isBB(){
	if (context.getUserAgent().getUserAgent().indexOf("BB10") > -1 && context.getUserAgent().getUserAgent().indexOf("Touch") > -1){
		return true;
	}else{
		return false;
	}
}

function isPhone(){
	var useragent = context.getUserAgent().getUserAgent();
	if ((useragent.indexOf("iPhone") > -1 && useragent.indexOf("Mobile") > -1) || 
			(useragent.indexOf("BB10") > -1 && useragent.indexOf("Touch") > -1) || 
			(useragent.indexOf("Android") > -1) || (useragent.indexOf("Windows Phone") > -1)){
		return true;
	}else{
		return false;
	}
}

In UnpBootResources cc:

javascript:if (isIOS()){
			return "unp/css/bootcards-ios.min.css";
		}else if (isAndroid()){
			return "unp/css/bootcards-android.min.css";
		}else if (isWindowsPhone()){
			return "unp/css/bootcards-android.min.css";
		}else if (isBB()){
			return "unp/css/bootcards-android.min.css";
		}else {
			return "unp/css/bootcards-desktop.min.css";
		}

javascript:if (isIOS()){
			return "unp/unplugged-ios.css";
		}else if (isAndroid()){
			return "unp/unplugged-android.css";
		}else if (isWindowsPhone()){
			return "unp/unplugged-android.css";
		}else if (isBB()){
			return "unp/unplugged-android.css";
		}else {
			return "unp/unplugged-desktop.css";
		}

Thanks for greats controls!
