### ISSUE TITLE
Sampler app - mobile toggle switch does not work in some instances

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#267]
This is in the Sample App from OpenNTF included in the download. Recreate using Chrome on desktop.
Open Contacts and select Add from list. 'Mobile Enabled' green toggle switch works.
Close new doc, click/tap on an entry and then re-tap Add; 'Mobile Enabled' green toggle switch no longer works - may have to do this for a couple of entry to see it not working.

**Comment by whitemx** [comment]
Could you have a retest of this one please? I've tested in multiple browsers and it all seems to be working.

We have upgraded the version of Bootcards since this was reported so maybe it was fixed with that?
