### ISSUE TITLE
PC browser navigation

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#273]
In the PC browser interface, the navigation menu in the header bar should use pull-down lists rather than link to items in a workspace.  For example, when you go to the Sampler home screen and then click on “Lists” in the header bar you should see a pull-down menu of available Lists.  The user then clicks on the List they want, instead of jumping to a new screen with the available lists shown in a Workspace summary card.  This cuts out one unnecessary screen transition.

This may need an enhancement to Bootcards to make this work.

**Comment by whitemx** [comment]
Check with @markleusink to see where this stands with Bootcards.

**Comment by markleusink** [comment]
Is there a change needed for this at the Bootcards side? The desktop styles are standard Bootstrap and the Bootstrap header has the dropdown option already built-in.

**Comment by whitemx** [comment]
This change will also incorporate the new "navbar-double" functionality from Bootcards: http://clients.jackherbert.com/unplugged4/multi-nav.html
