### ISSUE TITLE
Full /Partial refresh not working in Modal Edit or Add boxes

### ISSUE THREAD

**Issue by NeilEvans** [teamstudio/xcontrols-domino#275]
When using 2 combo boxes with @Dblookups, selections do not refresh when called from xcontrols viewer/editor, same page when put within a dialog box performs refreshes successfully

**Comment by whitemx** [comment]
We do not currently support standard XPages partial refreshes when using the FormEditor control. You can write your own using a jQuery Ajax GET request in combination with an XAgent style XPage: http://www.wissel.net/blog/d6plinks/SHWL-8BYMW8
