### ISSUE TITLE
DatePicker not working in browser

### ISSUE THREAD

**Issue by NeilEvans** [teamstudio/xcontrols-domino#276]
The DatePicker works in IOS and IOS Safari Browser but does not work on windows desktop browsers

**Comment by whitemx** [comment]
This depends on the browser being used, Chrome for example would work, but IE will not. You are free to add your own date picker as required.

**Comment by sives** [comment]
In my opinion, we should be supporting modern versions of IE with the XControls project, setting the bar at IE 9 or IE 10.

**Comment by sives** [comment]
Let's discuss on Skype.
