### ISSUE TITLE
Datepicker not working on ios when an UnpBootRichTextEditor on same xpage

### ISSUE THREAD

**Issue by NeilEvans** [teamstudio/xcontrols-domino#279]
keyboard pops up and no datepicker when the richtexteditor is used, this issue occurs in the sample on the CalendarEntry custom control, the desktop version (on Chrome) works ok

**Comment by whitemx** [comment]
This is working fine on iOS8 (iPhone / iPad). Could you let me have any more details to try and track down the bug please?
![2015-01-09 07 25 37](https://cloud.githubusercontent.com/assets/856638/5676657/80a200e2-97d1-11e4-8e93-3786c3d938b3.png)

**Comment by whitemx** [comment]
I should make a note that on the desktop (IE & FF) we're adding a date picker as part of #276 but this doesn't affect Chrome or iOS.

**Comment by NeilEvans** [comment]
Hi,
Managed to get a screenshot of the issue
![xcontrol_mmem](https://cloud.githubusercontent.com/assets/2086423/5697204/8f8aafb8-9a3e-11e4-8cea-e3d2e9b232b1.jpg)

**Comment by NeilEvans** [comment]
The One thing ( probably the most important) I am using unplugged, just tried it and it works fine on safari on ipad but not from within unplugged

**Comment by edm00se** [comment]
Getting similar erroroneous behavior (matches your screen shot) with the RT Editor. (issue #310)

**Comment by whitemx** [comment]
As of v1.3.1 we have removed the RT Editor from the Sampler app. However, from your screenshot it looks like we're encountering a JavaScript error when the page loads.

This is not something that I am seeing on my devices for testing, so I'll need to ask you to do the following:

1) In Unplugged, go to Settings and toggle the Developer Server switch
2) Using the "Dev Server" URL that Unplugged gives you, open the URL in Chrome on your desktop
3) Navigate to the Calendar page and attempt to edit an entry
4) See if there are any JavaScript errors.

If you can let me know the outcome of that then I should be able to help more.

Matt

**Comment by NeilEvans** [comment]
Hi Matt,
This is the console log when I run it

dojo.js:14 Synchronous XMLHttpRequest on the main thread is deprecated 
because of its detrimental effects to the end user's experience. For more 
help, check http://xhr.spec.whatwg.org/.
Contacts.xsp:9 GET 
http://192.168.0.20:8311/NotesApp01/MMEM!!XControlsSampler_v1_3.unp/unp/moment-with-locales.js 
404 (Not Found)
bootstrap-datetimepicker.js:39 Uncaught ReferenceError: moment is not 
definedbootstrap-datetimepicker.js:39 dpgIdbootstrap-datetimepicker.js:44 
(anonymous function)
Contacts.xsp:9 GET 
http://192.168.0.20:8311/NotesApp01/MMEM!!XControlsSampler_v1_3.unp/unp/quill.js 
404 (Not Found)
jquery-2.0.3.min.js:4 Resource interpreted as Font but transferred with 
MIME type text/html: "
http://192.168.0.20:8311/NotesApp01/MMEM!!XControlsSampler_v1_3.unp/unp/fontawesome-webfont.woff?open&v=4.1.0
".
unplugged.js:212 Uncaught ReferenceError: Quill is not 
definedunplugged.js:212 unp.initRichTextunplugged.js:516 (anonymous 
function)jquery-2.0.3.min.js:4 x.extend.eachjquery-2.0.3.min.js:4 
x.fn.x.eachjquery-2.0.3.min.js:6 (anonymous function)jquery-2.0.3.min.js:4 
x.Callbacks.ljquery-2.0.3.min.js:4 
x.Callbacks.c.fireWithjquery-2.0.3.min.js:6 kjquery-2.0.3.min.js:6 
x.ajaxTransport.x.support.cors.e.crossDomain.send.t

Regards,
Neil Evans,
IT Systems Development Manager.
M.M. Electrical Merchandising

**Comment by whitemx** [comment]
OK so it looks like some files are missing. Could you confirm that the file resources:
* unp/moment-with-locales.js
* unp/quill.js
are present in the database.

If they are, then the next step is to remove the database from Unplugged and then re-sync. I have seen situations where sometimes file resources don't get sent down to the device, normally a resync fixes this.

Matt

**Comment by NeilEvans** [comment]
Hi 
File resource looks ok
doesn't have the issue on the desktop version
Tried deleting databases from within settings, no change.
deleted and re-installed unplugged from app store, no change

I am having the same issue with the calendar on v1.3 ( have a call logged 
with teamstudio) 
they can't seem to solve it but on checking using the dev server it is the 
same issue with missing js 
any thoughts greatly appreciated


Regards,
Neil Evans,
IT Systems Development Manager.
M.M. Electrical Merchandising

**Comment by whitemx** [comment]
One thing to try is to go into the Unplugged.nsf app on your server, then go to settings and find the "Max Response Size". Try increasing this, my setting is 512kb.

**Comment by NeilEvans** [comment]
Hi Matt,
That fixed both the issues,
Thanks I will let the TS tech support know.
 should I ever have to up the setting again ?


Regards,
Neil Evans,
IT Systems Development Manager.
M.M. Electrical Merchandising

**Comment by whitemx** [comment]
I hope not, I'll update the documentation as well.

**Comment by edm00se** [comment]
Matt, I can confirm this also fixed the Quill/RT Editor issue.
