### ISSUE TITLE
Categorised List documentation for v1.3

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#282]
I propose a separate section in the docs on Categorized Lists following on from the Flat List section.  As one of the four fundamental types of List in the UI designer's toolkit, these are under-documented at the moment.  (I understand that a Categorized List in programming terms is just a type of Flat List, but if you are a UI designer looking for guidance on how to create Categorised Lists after seeing them in the Sampler app, it is currently very hard to find).

**Comment by whitemx** [comment]
Documentation updated.
