### ISSUE TITLE
XControls.org home page credits

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#290]
The credits in the Jumbotron should read:
created by @mattwhite, @sives and @jackherbert and sponsored by Teamstudio.

i.e. the same as in the About text

**Comment by mattwhite** [comment]
Hey, I'd love to take credit for this, but I think you have the wrong Matt White :)

**Comment by whitemx** [comment]
Our name is far too common Matt :-)

Anyway, closing off this issue now.
