### ISSUE TITLE
Upload Card bug

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#293]
On my iPad in Unplugged, when you tap on "Select Photo" nothing happens.  It should take you to the photo library.   I'm concerned that the Rotate and Upload functions may also be broken since I wasn't able to test them.  

This function is also broken on Unplugged on Android

(I've just re-synced on iOS and it appears to be working again)

**Comment by whitemx** [comment]
Seems to be working fine for me.
