### ISSUE TITLE
XMark benchmark

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#294]
The Mark benchmark needs to be run and the performance metrics checked against the v1.1 and 1.2 releases to check that there is no unexpected performance regression.

**Comment by whitemx** [comment]
The performance is roughly equivalent to v1.0. Looking at the numbers it seems that the numbers for 1.2 were not very realistic for some reason.

![1-3-chart](https://cloud.githubusercontent.com/assets/856638/5807197/b3821516-a018-11e4-9d5d-0e4dea2fed8b.png)
![1-3-timings](https://cloud.githubusercontent.com/assets/856638/5807198/b3a4e5dc-a018-11e4-93b5-3e3c97538f45.png)
