### ISSUE TITLE
Missing Form Card in PC browser Sampler

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#296]
For some reason the Form Card is not being displayed in the list of available Cards

**Comment by whitemx** [comment]
It's showing up for me, am I looking in the same place as you:
![screen shot 2015-01-19 at 20 22 50](https://cloud.githubusercontent.com/assets/856638/5807230/05e66bea-a019-11e4-861b-03ed6033b923.png)

**Comment by sives** [comment]
Seems like this was a transient glitch.  It's working for me now.
