### ISSUE TITLE
UnpBootAccordionView - Load More does not work

### ISSUE THREAD

**Issue by reidcanavan** [teamstudio/xcontrols-domino#309]
The Load More when pressed will simply disappear as opposed to loading more data.

This may be related to the issue found with ajaxload = No not working.  Suspicion regarding sessionScope / viewScope not having values for the UnpAccordionViewList to work with?

Loaded / signed the sample database for 1.3 and finding that the Accordion view for that is working.  Can't seem to isolate any real differences in the code being used to determine why its not working.

Not sure if the issue is due to the volume of data found in the view being used?  ( Approx 22,000 records ).

**Comment by whitemx** [comment]
Would it be possible to have a look at your application with the issue? We've tested locally with databases up to 5000 docs, so I don't *think* that it's anything to do with the volume of data.

**Comment by reidcanavan** [comment]
What is the best way to send you the application in question?  I can
provide you a login to see it via the web?

Reid

**Comment by whitemx** [comment]
Hi Reid,

You can send the details to me at matt@ldcvia.com and I'll try and have a look this week.

Matt

**Comment by reidcanavan** [comment]
Just updated to 1.3.1 and tried and the issue appears to still be present.  I will send you an e-mail with a link to the full database for your reference.

**Comment by reidcanavan** [comment]
Full database is posted with a link to download sent to your e-mail ( matt ).

**Comment by reidcanavan** [comment]
I adjusted the UnpBootAccordionViewList XPage to use 500 instead of 12 and it appears to be loading all the content for the category.  Not sure if that helps?

**Comment by whitemx** [comment]
I finally got a chance to look at this (apologies for the delay). There are two issues in the app:

In the UnpViewLocatesByProperty XPage, for detailcolumn and summarycolumn you need to use the column titles in the view, not the programmatic names of the columns. When referencing the view, it's better to use the alias of the view as we have a bug with passing view names with backslashes in them.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xp:view xmlns:xp="http://www.ibm.com/xsp/core" xmlns:xc="http://www.ibm.com/xsp/custom"
	xmlns:unp="http://unplugged.teamstudio.com">
	<unp:UnpBootResources></unp:UnpBootResources>
	<xc:tofeHeader></xc:tofeHeader>
	<div id="main" class="container">
		<div class="row fullheightrow">
			<unp:UnpBootAccordionView xp:key="facet_1"
				viewname="v_unp_locateProperty"
				xpagedoc="UnpDocLocate.xsp" ajaxload="No"
				detailcolumn="locationNote" summarycolumn="streetNo"
				title="Locates by Street Name" id="viewStreet"
				expandfirstcategory="no">
			</unp:UnpBootAccordionView>
		</div>
	</div>
	<unp:UnpBootFooter synctype="alldbs"></unp:UnpBootFooter>
</xp:view>
```

In the sample above, I've changed the column titles in the view design to match the programatic names (it doesn't matter in this case as the view is hidden from users) and I've changed the view alias.

Matt
