### ISSUE TITLE
Editing Card Bug (still experiencing)

### ISSUE THREAD

**Issue by edm00se** [teamstudio/xcontrols-domino#310]
I'm still experiencing this (ref issue #287) with the current version of the sampler app, in iOS 8.1.3 (current) on an iPad w/ Retina (1st w/ Retina, 4th gen-ish?) and iPhone 6 (also iOS 8.1.3), in the UnPlugged app. UnPluged app is current from the App Store, sampler db freshly copied, UnPlugged server is current build (3.1.22.710).

Instead of showing the content and letting me edit the RT fields, it shows the "hello world" text. The UnpBootRichTextRead is fine, showing the details entered. When access via mobile Safari (same device) or from desktop, there is no issue and the field lets me edit as expected.

**Comment by whitemx** [comment]
Hi,

We've had a project meeting today and we have made the decision to remove the RichTextEditor control at the moment. The editor plugin which we use (QuillJS) is not reliable enough yet.

Matt

**Comment by edm00se** [comment]
Noooooooo!

I really liked it (when it was working). Are there any details on what's going on that would need to get sorted with the issue _inside_ the UnPlugged app?

**Comment by whitemx** [comment]
Sorry,

I wasn't clear, we'll be removing the RichTextEditor from the Sampler application, but it will still be available in the controls for you to use at your own risk (!). 

Basically the RT Editor needs to be loaded with a full page load, it becomes unreliable when loading pages with Ajax, so I think that is the underlying problem that you're experiencing.

Matt

**Comment by edm00se** [comment]
Aha. Good to know. For a couple specific use cases, those are terms I believe I can accept. Thanks for the update.

**Comment by whitemx** [comment]
This will be fixed as part of #279

**Comment by edm00se** [comment]
This looks to be resolved as part of #279.
