### ISSUE TITLE
Calendar Categories and Colors

### ISSUE THREAD

**Issue by whitemx** [teamstudio/xcontrols-domino#313]
Cross posted from http://www.openntf.org/main.nsf/project.xsp?r=project/XControls/discussions/894FC5878EA0AA6E86257DFE005097CC
Dear Staff,

first of all thank you very much for this controls set … we are using it for a new XPages project and we find it amazing.

However we have this “problem” with the Calendar control. 
We need to use only one calendar to show entries of many users. 
We can take advantage of Category property for this purpose but it's not enough. We need to set specific entries colors for every user.

We cannot find (reading official docs) specific properties for colors settings.

Which is the best way to achieve our goal?

Thank you in advance, 
Christian

**Comment by whitemx** [comment]
When you use the catfield setting (you pass in the name of a field to examine on each document) each different value will be assigned a color and that color will be used through the calendar entries. If you look at the June 2015 data in the Sampler application you will see this in action. So you can apply a filter using the filter property and then group different calendar entries using the catfield.

If this doesn't meet your needs please let us know and we'll see what we can do. Or if you want to modify the calendar you can submit the changes back to us and we'll incorporate them into the main project.

**Comment by jacktric** [comment]
Thank you for your support whitemx!

Yes, no problems about the use of filtering and categorization.

I had a look at the sample application.
This colors are used:
- #007aff (standard entries)
- rgb(197, 120, 82) (categorized entries)

What I need is to use, and set programmatically, different colors.

Any tricks about this? 
Maybe some "hidden" property or function?
Or maybe I can change stardard colors in a easier way?

Thank you.

**Comment by whitemx** [comment]
In your calendar XPage in the beforeRenderResponse event, you can define sessionScope.calendarcolors to override the default colors like so:

```javascript
sessionScope.calendarcolors = ['#77b4f9', '#074025', '#176f17', '#50cc86', '#3a61a4', '#b68e8d', '#9f26aa', '#6daa1c', '#b31f1a', '#6f377e', '#390a12', '#edcc89', '#2840e0', '#c63a9c', '#c2bed1', '#0d306f', '#09bb90', '#34ea03', '#b7f1f4'];
```

**Comment by jacktric** [comment]
This could be exactly what I need.
I'll try it as soos as possible and I'll keep you informed.

Thank you.

**Comment by whitemx** [comment]
Assuming this is fixed.
