### ISSUE TITLE
Typeahead always defaults to the first name listed

### ISSUE THREAD

**Issue by AdyMakombo** [teamstudio/xcontrols-domino#314]
On an iOS device, in a field with typeahead enabled, when a user clicks on any of the names in the drop-down, on the next screen it always defaults to the first name listed (in this case Jill Stuber in the screen shot). 

The Company field in the Sampler app has the same behavior.

On the opposite, the typeahead feature works well in a browser.

![type1](https://cloud.githubusercontent.com/assets/3041329/6753223/c3ab2538-cf14-11e4-82a6-f31908ba5243.PNG)

**Comment by whitemx** [comment]
Tested on Android and it works fine, so definitely a mobile iOS issue
