### ISSUE TITLE
fileUpload not work in any platform

### ISSUE THREAD

**Issue by cherifAlimat** [teamstudio/xcontrols-domino#315]
I have inserted a fileUpload control in the PersonEdit.xsp. It appear. Browse file for upload work. But when i save the file is not saved.

I have inserted these lines between the Phone and the Details :
				<div class="form-group">
					<xp:label styleClass="col-xs-4 control-label" for="photo"
						value="Photo"></xp:label>				
					<div class="col-xs-8">
					     <xp:fileUpload id="thumbnail" value="#docedit.thumbnail}">                     
                                            </xp:fileUpload>
					</div>
				</div>

I have also tried to insert PhotoCard and other case UnpBootPhotoUpload, but it don't work.
Is there an issue ?

**Comment by whitemx** [comment]
We do not currently support file uploads.
