### ISSUE TITLE
UnpFlatView does not fully refresh after adding a new item

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#320]
Use the newlink property in the UnpFlatView control and ajax in a new doc/xpage. Use a UnpFormEditor and set the standard buttons to true and set the viewxpage property back to the xpage with the UnpFlatView control (UnpMain) complete the form and save the new doc.
The list with the original contents is displayed. A refresh of the browser shows the new item in the list.

**Comment by whitemx** [comment]
From Rich: I think this may be a 
regression bug? Didn’t we see this before and you fixed it? 
(FlatViewList refreshing after adding a new item?) - You can recreate 
using that Expenses app I send - add a new Expense Report from the 
FlatViewList.

**Comment by whitemx** [comment]
The thing that was changed previously was when updating existing documents. This would be a new feature.

**Comment by RichSharpe** [comment]
Quick fix (workaround): add a client side JS function in the callback property of the UnpFormEditor contained in the 'new' XPage:
     \<unp:this.callback>
    <![CDATA[#{javascript: return ("refreshListfromNewReport('" + getDbPath() + "')");}]]>
    \</unp:this.callback>

The CSJS function could do wahtever logic you needed and then add a location.href call at the end e.g:
function refreshListfromNewReport(dbPath){
	... optional code here   ...
   window.location.href = dbPath + "/UnpMain.xsp";
}

**Comment by whitemx** [comment]
I've changed the way the callback works so that the parameters required to run unp.clearsearch are passed to it. You can then choose to with them what you will :-)

There's just too many variables to add a simple switch to load the data after saving.

For an example, see the sampler app, custom.js line 391
