### ISSUE TITLE
Doco "Getting Started" Max Response Size

### ISSUE THREAD

**Issue by mickmoignardOAC** [teamstudio/xcontrols-domino#323]
The doco at http://xcontrols.org/public/docs.html#getting-started says, in a blue box:  "Remember to increase the "Max Response Size" in settings to 512Kb".  Two questions
-What "settings" is that?  Can't see it in either of the Application Configuration pages.  Or are you referring to the Server/web site config in the directory, or what? 
- Why? What won't work if this change is not made?

**Comment by whitemx** [comment]
This is if you're using Unplugged on mobile devices. I've updated the documentation page. Thanks

**Comment by mickmoignardOAC** [comment]
Matt

Cheers, thanks.

Mick

____________________________________________________

Mick Moignard
Software Developer
OAC Actuaries and Consultants

mick.moignard@oacplc.com  |  +44 (0)20 7278 9500  |  www.oacplc.com  |  
www.monetfinancialmodelling.com

Progress with Confidence

Follow us:  Twitter  |  LinkedIn
