### ISSUE TITLE
UnpBootAccordionView "Load More..." function does not work if viewname contains a "\" character

### ISSUE THREAD

**Issue by kordisch** [teamstudio/xcontrols-domino#327]
When using the Accordion View, if the viewname contains a slash "\" (ie to group views under a folder, eg. viewname="Z - Label Table\Labels By ProfitCenter") the "Load More..." function does not work.  When you click the "Load More..." entry, the "Load More..." entry is removed, but no additional results are returned.  The workaround is to use a view alias that does not contain a "\" character.  Not a big deal, just thought I would point it out if anyone else experiences this.

**Comment by reidcanavan** [comment]
I did report an issue with the Load More not working.  I presumed it was due to the volume but I will definitely give this a try.  Basically I put anything against Unplugged into a view "Unplugged\<VIEW NAME>" which would explain why none of the views work with the load more button.
