### ISSUE TITLE
User is presented with a blank screen in portrait mode

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#332]
If the openFirstEntry property in UnpFlatView is false, opening an xpage in portrait mode on a tablet results in a blank screen with a 'list' link at the top.
Can we show the list by default if openFirstEntry is false?

**Comment by whitemx** [comment]
That's more of a bootcards issue than XControls. My advice would be to add some static text to a div that is displayed if you're not automatically loading a document.
