### ISSUE TITLE
UnpBootFormEdit Control does not render correctly on re-orientation (when in FullPaggeMode)

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#334]
If you open in landscape and orient to portrait the form re-sizes to the width of the control with space for a list (2/3 screen width size)

**Comment by whitemx** [comment]
To fix this, if you add a class of "full-width" to the doccontent div then orientation changes will not automatically add the col-sm-7 class which is what is forcing the narrow width.

**Comment by whitemx** [comment]
You'd need to update to the latest build, there's a change in unplugged.js which looks for the class.
