### ISSUE TITLE
UnpHeader title area too small for phones

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#335]
The 'Save and close buttons get overwritten by the title if its more than say, 14 chars. 
Can we wrap the title over 2 lines? I think this would be an appropriate design decision.

**Comment by sives** [comment]
I agree with this

**Comment by RichSharpe** [comment]
Workaround:
 1. Open UnpBootHeader custom control (or copy and rename so it won't get overwritten) - go to line 229 <xp:text value="#{javascript:compositeData.title}" and in the xp:text properties change the Content Type from text to HTML
 2. Add a style attribute to this tag: style="margin-bottom:10px;"
 3. In your common header XPage go to the xp:UnpBootHeader and in the title you can write "First Line  <br/>  Second line " (or) + docview.whateverField (for hte second line)

**Comment by whitemx** [comment]
This is broken as a result of upgrading to Bootcards 1.1.3. Will need to raise this as an issue with Mark.
