### ISSUE TITLE
Cancel button does not work as expected - UnpBootFormEditor

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#336]
The Cancel button on the full screen mode uses history.go(-1).
This should be a custom property for this control. Currently if I have a link to a second XPage within my UnpBootFormEditor and navigate to this XPage, going back to the UnpBootFormEditor and tapping 'Cancel' takes me back to the second XPage, not the XPage that called the UnpBootFormEditor.

**Comment by whitemx** [comment]
Added a new custom property called "fullpagemodecancellink" which will be used for the cancel link when fullpagemode is true. It will be ignored otherwise. If this new property is not supplied then the current history.go(-1) is used.
