### ISSUE TITLE
Calendar formatting problem -- cell widths take up full row

### ISSUE THREAD

**Issue by Telemanage** [teamstudio/xcontrols-domino#341]
Hi,  I am developing a calendar with XControls 1.3.1, but the calendar display by month does not seem to be correct:  http://sampler.xcontrols.org/XControls.nsf/Calendar.xsp

![image](https://cloud.githubusercontent.com/assets/10204137/8211629/9339f066-14e5-11e5-9b14-4363e135eddf.png)
 
While the appointment docs are placed starting in the right position, their widths always extend to the end of the calendar window.  This is not how it is supposed to work, I don't think.

I have tried viewing this page on different browsers and devices with the same result.

Please advise.  Thanks.

**Comment by whitemx** [comment]
Thanks for the heads up, it was a data issue on the demo server that should be fixed now.

**Comment by Telemanage** [comment]
OK, thanks, but what was the fix?  The XControls 1.3.1 Template has the same problem, and I am using that for my project.

Thanks  -E

**Comment by whitemx** [comment]
In the CalendarEntries view, all the documents had their start date in 2015, but the end date in 2016, so a simple formula agent to set the EndDate year to 2015 is all that is required to fix the data.
