### ISSUE TITLE
calendar view

### ISSUE THREAD

**Issue by PatrickKwinten** [teamstudio/xcontrols-domino#342]
my calendar view is full with entries?

![calendar](https://cloud.githubusercontent.com/assets/7702330/8231826/6a12a2aa-15cb-11e5-9cce-56d8097ae155.JPG)

**Comment by whitemx** [comment]
If this is with the downloaded sampler database, there is bad data. If you go to the calendar entries view and modify the documents to have end dates in 2015 rather than 2016 then it should work ok! Apologies
