### ISSUE TITLE
UnpBootFormEditor still saves the doc if presavecallback function returns false 

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#344]
Add a function call to the presavecallback that returns false - the doc still saves and navigates to the xpage defined in viewxpagename rather than halt processing and return to the xpage with the UnpBootFormEditor control

**Comment by whitemx** [comment]
This seems to be working for me, have you got an example I can test please?

**Comment by whitemx** [comment]
This issue is working properly after further testing.
