### ISSUE TITLE
Xcontrols Calendar layout issue

### ISSUE THREAD

**Issue by Telemanage** [teamstudio/xcontrols-domino#350]
Hi,  I reported an issue with the calendar controls here:
https://github.com/teamstudio/xcontrols-domino/issues/341
And the issue was closed before explaining what changes I need to make to fix the data issue that you fixed on your site.  I am still having the problem.

Please advise, thank you.

-E

**Comment by whitemx** [comment]
In the CalendarEntries view, all the documents had their start date in 2015, but the end date in 2016, so a simple formula agent to set the EndDate year to 2015 is all that is required to fix the data.

**Comment by Telemanage** [comment]
Grazzi
