### ISSUE TITLE
Calendar Entry element height is 0 in by week and by day views

### ISSUE THREAD

**Issue by Telemanage** [teamstudio/xcontrols-domino#351]
![image](https://cloud.githubusercontent.com/assets/10204137/8853708/fe37cd7e-3129-11e5-9ad1-8205e2fc6732.png)

The height of the calendar entries is set to '0' and are not visible.  This is the same in the by Day view, too.

Please let me know the fix as well so that I may implement it in my application.

Thank you,

-E

**Comment by Telemanage** [comment]
UPDATE: this occurs when StartDate = EndDate

Cheers  -E

**Comment by Telemanage** [comment]
Thanks -- any chance you could tell me what the fix was so that I do not have to download the entire template again?  Thank you.

**Comment by whitemx** [comment]
You can always see the changes when I do a commmit, by clicking the link above that goes here: https://github.com/teamstudio/xcontrols-domino/commit/2bc50bd74308aaf7b06da815e59a0029dd120b5a
