### ISSUE TITLE
Typeahead doesn't work with very large lists

### ISSUE THREAD

**Issue by whitemx** [teamstudio/xcontrols-domino#354]
Reported by Ady Makombo

If the view that contains the lookup list for typeahead results is very large then no results are returned.

**Comment by AdyMakombo** [comment]
Hi Matt,

Will you have the time to look at this issue for the next release of the XControls?

Ady

**Comment by whitemx** [comment]
Hi Ady

As things stand I'm not actually sure when the next release of XControls
will be, I have a call with Steve booked for 15th September. I'll make sure
it's included in the list that we discuss.

Matt

On Wed, 2 Sep 2015 at 14:01 AdyMakombo <notifications@github.com> wrote:

> Hi Matt,
>
> Will you have the time to look at this issue for the next release of the
> XControls?
>
> Ady
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/teamstudio/xcontrols-domino/issues/354#issuecomment-137065954>
> .
>
-- 

Matt White

Phone - +44 7767 384970

E-Mail - matt@ldcvia.com

Personal Blog - mattwhite.me

Twitter - @mattwhite

**Comment by whitemx** [comment]
Ady,

I've committed a change which seems to work OK for me in testing. I am concerned that there may well be performance issues on large data sets however when using Unplugged. Unplugged doesn't support FTSearch nor some of the more advanced view navigation utilities (such as NotesViewNavigator and ViewEntryCollection.getEntry) so I have to manually loop through the view to find entries matching the query.

Have a test of the latest version and see what you think.

Matt

**Comment by AdyMakombo** [comment]
Hi Matt,

I have tested the new version by replacing the code of the UnpSearchAhead XPage.  For now, I don’t see any difference with the previous version.

However, the customer reported that when she was trying to display 232+ records, the typeahead selection list was empty.  In my case, with 400+ records, using both the old and the new versions, the typeahead selection list is displayed BUT I can only select one of the first 8 records of the list.  There is no way to scroll down the list and select the for example 9th or 10th item.

Ady

![typeahead](https://cloud.githubusercontent.com/assets/3041329/9787262/9157f968-57c1-11e5-9416-c9e2d52ee781.png)

PS: BTW, in this test, I removed the @Unique to be able to return multiple records even if the job # is exactly the same.

**Comment by whitemx** [comment]
Ady,

Just to confirm, where did you test the code from?

Matt

On Thu, 10 Sep 2015 at 12:48 AdyMakombo <notifications@github.com> wrote:

> Hi Matt,
>
> I have tested the new version by replacing the code of the UnpSearchAhead
> XPage. For now, I don’t see any difference with the previous version.
>
> However, the customer reported that when she was trying to display 232+
> records, the typeahead selection list was empty. In my case, with 400+
> records, using both the old and the new versions, the typeahead selection
> list is displayed BUT I can only select one of the first 8 records of the
> list. There is no way to scroll down the list and select the for example
> 9th or 10th item.
>
> Ady
>
> [image: typeahead]
> <https://cloud.githubusercontent.com/assets/3041329/9787262/9157f968-57c1-11e5-9416-c9e2d52ee781.png>
>
> PS: BTW, in this test, I removed the @Unique <https://github.com/Unique>
> to be able to return multiple records even if the job # is exactly the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/teamstudio/xcontrols-domino/issues/354#issuecomment-139211891>
> .
>
-- 

Matt White

Phone - +44 7767 384970

E-Mail - matt@ldcvia.com

Personal Blog - mattwhite.me

Twitter - @mattwhite

**Comment by AdyMakombo** [comment]
Hi Matt,

I tested it from my iPad and from Chrome.

Ady

**Comment by whitemx** [comment]
It sounds like I need to see the customer's database, as it's working fine for me with thousands of documents in a view.

With regards to not being able to scroll, the typeahead is not a combo box, it only offers options to save typing, it doesn't display all possible options. As you type the options should refine themselves to become more relevant.

**Comment by RichSharpe** [comment]
Is the lookup DB in the same DB as the XControls? I have an issue (which may need another ticket) if the lookup is in a different DB the search and type-ahead does not work. The UnpSearchAhead XPage (line 9) uses a DbClomun with @DbName whaich assumes the same DB. Most of the time I use the XControls I use an MVC approach and the data is in a separatet nsf. So really the UnpSearchAhead needs to see if dbName is a URL parameter and also UnpFlatViewList XPage needs to check for this as it uses the global database obj (current DB) on line 21.

**Comment by whitemx** [comment]
I had changed this while updating the code that I recently checked in.

**Comment by AdyMakombo** [comment]
I have copied the database on our FTP server in the \NEFS folder. You can also find the database here: \\Dev01\Development\External\NEFS\PhoneAppTEST.nsf.

This version of the application contains 862 job codes and it works well. It starts failing as soon as I copy and paste 1 job code in the same application. (You can copy and paste an existing document).

So, with 862 job codes the app works well but with 863 job codes it starts crashing.

**Comment by whitemx** [comment]
Right, I had completely got the wrong end of the stick with this, I'm going to commit a small change to unplugged.js that will allow you to choose whether you use a local lookup list (to avoid using AJAX requests), or a typeahead list using Ajax for large data sets.

In the latter case, the markup for the autocomplete field will be something like this:

````xml
<xp:inputText id="JobNumField" value="#{docedit.Job}"
	styleClass="required form-control typeahead JobNum" autocomplete="off">
  <xp:this.attrs>
    <xp:attr name="searchahead" value="UnpSearchAhead.xsp?chosenView=UnpJobSearch"></xp:attr>					
  </xp:this.attrs>
</xp:inputText>		
```

**Comment by AdyMakombo** [comment]
Hi  Matt,


I have made the recommended changes a) in the typeahead field and b) in
Unplugged.js. Unfortunately, I can't see any difference. Did I miss
something?





*Typeahead field*

<xp:inputText id=*"EPTL_Job"* value=*"#{docedit.EPTL_Job}"*

styleClass=*"required form-control typeahead JobNum"* autocomplete=*"off"*>




                <xp:this.attrs>

                               <xp:attr name=*"onChange"* value=
*"setLocation();"*></xp:attr>


                               <xp:attr name=*"searchahead"* value=
*"UnpSearchAhead.xsp?chosenView=UnpJobSearch"*></xp:attr>
                               </xp:this.attrs>

</xp:inputText>



*Unplugged.js*



unp.initAutoComplete = *function*() {

                $(".typeahead").each( *function*() {

                               *var* jslist = $(*this*).attr('jslist');

                               *if* (*typeof* jslist !== *typeof*
*undefined* && jslist !== *false*){

                                               $(*this*).typeahead({source:
eval($(*this*).attr('jslist')), autoSelect: *false*});

                               }*else*{

                                               //We must be looking for a
remote list

                                               *var* viewid = $(*this*
).attr('searchahead');

                                               $(*this*).typeahead({

                                                               source:
*function*(query, process) {


*return* $.ajax({

                                               url: viewid + "&query=" +
query,

                                               dataType: 'json',

                                               success: *function* (data) {

                                                   *return* *typeof* data
== 'undefined' ? *false* : process(data);

                                               }

                                           });

                                                               }

                                               })

                               }

                });

}



On Wed, Oct 21, 2015 at 1:24 PM, Matt White <notifications@github.com>
wrote:

> Right, I had completely got the wrong end of the stick with this, I'm
> going to commit a small change to unplugged.js that will allow you to
> choose whether you use a local lookup list (to avoid using AJAX requests),
> or a typeahead list using Ajax for large data sets.
>
> In the latter case, the markup for the autocomplete field will be
> something like this:
>
> <xp:inputText id="JobNumField" value="#{docedit.Job}"
>     styleClass="required form-control typeahead JobNum" autocomplete="off">
>   <xp:this.attrs>
>     <xp:attr name="searchahead" value="UnpSearchAhead.xsp?chosenView=UnpJobSearch"></xp:attr>
>   </xp:this.attrs>
> </xp:inputText>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/teamstudio/xcontrols-domino/issues/354#issuecomment-149859897>
> .
>



-- 
Regards,


*Ady MAKOMBO*
Technical Consultant
Teamstudio Europe Limited
Direct : 00 33 1 40 21 42 34
Fax : 00 33 1 40 21 42 35
Mobile : 00 33 6 26 81 86 30
Skype : ady.makombo
ady_makombo@teamstudio.com
www.teamstudio.com
