### ISSUE TITLE
Reccomendation: add some common/standard fields for debugging

### ISSUE THREAD

**Issue by RichSharpe** [teamstudio/xcontrols-domino#355]
Is it a good idea to add the following fields to UnpSaveDocument for analysis/debug purposes:
CREATED_BY
CREATED_DATE
LAST_MODIFIED_BY
LAST_MODIFIED_DATE
USER_AGENT (device used to create/modify the doc)

**Comment by whitemx** [comment]
I've used the following:
* UNPCREATEDBY
* UNPCREATEDDATE
* UNPMODIFIEDBY
* UNPMODIFIEDDATE
* UNPUSERAGENT
