### ISSUE TITLE
flatview/accordian dbname property does not work for remote server

### ISSUE THREAD

**Issue by gbozonline** [teamstudio/xcontrols-domino#362]
The flat view and accordian view database name always returns the dbname property but should return the db variable for remote servers (see commented line - return compositeData.dbname).

eg. laldev1!!applications/test.nsf

<xp:this.databaseName><![CDATA[#{javascript:if (compositeData.dbname != null){
  var db;
	if (compositeData.dbname.indexOf("!") > -1){
		db = session.getDatabase(@Left(compositeData.dbname, "!"), @RightBack(compositeData.dbname, "!"));
	}else{
		db = session.getDatabase("", compositeData.dbname);
	}
	
	if (db == null){
		return null;
	}else{
		//return compositeData.dbname;
		return db;
	}
}}]]></xp:this.databaseName>

**Comment by whitemx** [comment]
Hi @gbozonline could you confirm that you're seeing a problem here? When I test with the existing code everything is working fine.

**Comment by gbozonline** [comment]
Hey Matt,

Yes.  Absolutely.  If you look at the code for the UnpBootAccordianView - 
Custom Control you can see where it is setting the database for the view 
Data Source.

If the custom control parameter contains an '!' making it a remote server, 
the db variable is correctly set to get the database from the remote 
server.  So db is NOT Null.

However, the code goes on to check if db is Null.  If NOT Null, it should 
return 'db' rather than compositeData.dbname.

Let me know if you require any further information.  It was a simple 
workaround for me but the product is great and I just wanted to let you 
know so that you can fix it for the next release.

Cheers,

<xp:this.data>
                <xp:dominoView var="viewList"
                        viewName="#{javascript:compositeData.viewname}">
                        <xp:this.categoryFilter><![CDATA[#{javascript:if 
(isEmpty(compositeData.categoryfilter)){
        return null;
}else{
        return compositeData.categoryfilter;
}}]]></xp:this.categoryFilter>
                        <xp:this.databaseName><![CDATA[#{javascript:if 
(compositeData.dbname != null){
        var db;
        if (compositeData.dbname.indexOf("!") > -1){
                db = session.getDatabase(@Left(compositeData.dbname, "!"), 
@RightBack(compositeData.dbname, "!"));
        }else{
                db = session.getDatabase("", compositeData.dbname);
        }
        if (db == null){
                return null;
        }else{
                return compositeData.dbname;
        }
}}]]></xp:this.databaseName>
                </xp:dominoView>
        </xp:this.data>

Gary Brodie
Application Developer


P:
E:
W:
+61 3 9258 7448
gary.brodie@qenos.com
www.qenos.com




From:
Matt White <notifications@github.com>
To:
teamstudio/xcontrols-domino <xcontrols-domino@noreply.github.com>, 
Cc:
gbozonline <gary.brodie@qenos.com>
Date:
22/10/2015 01:32 AM
Subject:
Re: [xcontrols-domino] flatview/accordian dbname property does not work 
for remote server (#362)



Hi @gbozonline could you confirm that you're seeing a problem here? When I 
test with the existing code everything is working fine.

**Comment by whitemx** [comment]
When I return the db object rather than the dbname string, I get an error. I'm wondering if we have different versions of the Domino server or something like that?

**Comment by whitemx** [comment]
The check to see whether the database on the remote server is valid is probably overkill really, but once it is opened, I don't think it needs to be returned.

**Comment by gbozonline** [comment]
Hey Matt,

We are 9.0.1 FP3.

I think you might have gone down the exact same path that I did.  The 
custom control parameter value must actually have 2 x exclamations in it.

eg. "laldev1!!applications/qen00046.nsf"

So, if you put the 2 x exclamations in, the object returns successfully 
which is why you need to return the db object rather than the string.

Cheers,

Gary Brodie
Application Developer


P:
E:
W:
+61 3 9258 7448
gary.brodie@qenos.com
www.qenos.com




From:
Matt White <notifications@github.com>
To:
teamstudio/xcontrols-domino <xcontrols-domino@noreply.github.com>, 
Cc:
gbozonline <gary.brodie@qenos.com>
Date:
22/10/2015 06:06 PM
Subject:
Re: [xcontrols-domino] flatview/accordian dbname property does not work 
for remote server (#362)



When I return the db object rather than the dbname string, I get an error. 
I'm wondering if we have different versions of the Domino server or 
something like that?

**Comment by gbozonline** [comment]
No.  I think it is perfectly valid how you are doing it.  As per my 
response to your other email today I think it will make sense once that is 
working.

Cheers

Gary Brodie
Application Developer


P:
E:
W:
+61 3 9258 7448
gary.brodie@qenos.com
www.qenos.com




From:
Matt White <notifications@github.com>
To:
teamstudio/xcontrols-domino <xcontrols-domino@noreply.github.com>, 
Cc:
gbozonline <gary.brodie@qenos.com>
Date:
22/10/2015 06:10 PM
Subject:
Re: [xcontrols-domino] flatview/accordian dbname property does not work 
for remote server (#362)



The check to see whether the database on the remote server is valid is 
probably overkill really, but once it is opened, I don't think it needs to 
be returned.
