### ISSUE TITLE
Problems with Search

### ISSUE THREAD

**Issue by MikeAmberg** [teamstudio/xcontrols-domino#373]
There appears to be an issue with the Search when the UnpFlatViewer (1.5.1)  DetailColumn contains a notes date field, a notes time field or even a text derived date time value (i.e. @text(startdate)). the search refuses to return values although the type a-head works. Switching the field to a text (i.e. Venue) - alpha characters only restores search functionality

The List and Values are displayed properly

![image](https://cloud.githubusercontent.com/assets/15076546/10680016/233cdd82-78ea-11e5-83e2-98f9421b44fa.png)

![image](https://cloud.githubusercontent.com/assets/15076546/10680083/a7152060-78ea-11e5-9fc5-0c2e2b4c5dea.png)

BTW: The last @text shouldn't be needed its text already

**Comment by whitemx** [comment]
This should be fixed by the addition of the new option to use Full Text search rather than the old view search.
