### ISSUE TITLE
Name Picker Issue

### ISSUE THREAD

**Issue by ajaybmali** [teamstudio/xcontrols-domino#374]
we are facing difficulty to add name picker in the xControls Edit form. It does not pop up - we think this is because the Edit form is itself a pop up. If anyone has successfully added name picker to any xControls sample application, kindly let us know how it's done.
Please also let us know if you have any work-around; we tried type-ahead but that also doesn't seem to work, perhaps because we have a lot of data.

**Comment by whitemx** [comment]
Hi, I think your best best will be to use the upcoming 1.5.2 release which has support for large lists in typeaheads.
